title: Platform Engineering KB
description: Knowledge Base for Platform Engineering
theme: just-the-docs

url: https://bazaartechnologies.github.io/platform.github.io

aux_links:
  Repository: https://github.com/bazaartechnologies/platform.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Enable or disable the site search
search_enabled: true

# Heading anchor links appear on hover over h1-h6 tags
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 Bazaar Technologies. Distributed by an <a href=\"https://github.com/bazaartechnologies/platform.github.io/blob/main/LICENSE\">MIT license.</a>" 